title: IWU Chemistry
description: A clean GitHub Pages site using Bulma Clean Theme
url: "https://iwuchemistry.github.io"
baseurl: ""

permalink: pretty
favicon: /img/favicon.png
theme_color: '#ae1131'
#footer_menu: footer_menu
logo: /img/otthall.JPG

defaults:
  - scope:
      path: ""
    values:
      image: /img/otthall.JPG
      author: Nate Kitzmiller

remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - kramdown-parser-gfm
